### ISSUE TITLE
Example of testing EventHandler

### ISSUE THREAD

**Issue by rubiktubik** [gautema/CQRSlite#11]
Hi, great project!,

In your Samples you have examples of how to test the WriteModel especially the commands.(With the Help of your `Specification` TestHelper class)
Can you give a example how to test the EventHandlers and the Events?

Regards
Michael

**Comment by gautema** [comment]
Hi. I'm on vacation a few weeks with no computer, so I can't give any examples right now. Testing an event handler is a bit different than a command handler however since there's no fixed output type, like in the command handlers. Event handlers should be pretty straightforward to test just like any other unit or integration test.
