### ISSUE TITLE
Purpose of generic argument on IEventStore.Save<T>

### ISSUE THREAD

**Issue by petersondrew** [gautema/CQRSlite#17]
I had a question regarding `IEventStore.Save<T>`. The generic type argument is not used, therefore we have to rely on runtime type information in order to be able to serialize the events to a datastore. What is the purpose of this type argument?

**Comment by gautema** [comment]
The generic type argument is just there to give type information to the event store because it's available and might be used to store aggregates events differently. Do you have a problem with it or would you want something else out of it? I didn't get what you meant by that you have to rely on runtime type information. Are you taking about the event types?

**Comment by petersondrew** [comment]
After looking in the repository I see how it's used now, the aggregate type is passed as T, and any uncommitted events (which may be of any type) are passed in. To me the concept of an event store seemed aggregate-agnostic, but that may not always be the case.

I hadn't thought about receiving multiple uncommitted events of different types in `Save`, but since that can happen, we need to use the runtime type information of the events anyway if we want to know how to serialize/save them to the backing store.

Don't mind me, just still getting my head around this project I guess 😉. Thanks for the explanation.

**Comment by gautema** [comment]
No problem. You are correct that the event store probably should be aggregate agnostic. However, since the information is available, I figured it wouldn't hurt to provide it, and in case you want to do sharding based on aggregate type or something similar, it wouldn't hurt.
