### ISSUE TITLE
Would it make sense to have generic IEventStore implementation

### ISSUE THREAD

**Issue by feugen24** [gautema/CQRSlite#56]
The problem is that I want to add metadata to events, for example correlationId, issuer. I could derive from 
IEvent but I would need to create wrapper for IEventStore and maybe casts in other places.

So for example instead of:
`
Task<IEnumerable<IEvent>> Get(Guid aggregateId, int fromVersion, CancellationToken cancellationToken = default(CancellationToken));`

Could it be:

`Task<IEnumerable<T>> Get(Guid aggregateId, int fromVersion, CancellationToken cancellationToken = default(CancellationToken)) where T:IEvent;`

**Comment by feugen24** [comment]
also in the IEvent interface there is:

 Guid Id { get; set; }

but in the AggregateRoot , FlushUncommitedChanges there is

```
if (@event.Id == Guid.Empty)
 {
    @event.Id = Id;
 }
```
so more events have Id of the aggregate. So the Event.Id filed is more like Event.AggregateId.

'Id' would imply a unique identifier for events not a reference to the AggregateId

**Comment by gautema** [comment]
Hi.
I think making the eventstore generic would make the api more complicated and harder to use for most users. I've had a lot of people wanting more things to be generic throughout the years. Right now there are two open issues with people wanting more things to be generic. I try to keep things as easy as possible, because I think it's better to start with this framework and grow out of it, than to never start with it at all. If you need more fields on an event, I think a better approach would be to fork the project or copy the files in to your own code and change it there. 

As for the second comment, I think you might be right that it would be better to call it aggregateId, however the api is a bit hard to change now, since a lot of people are using it and changing it would make it very hard to upgrade to a new version.

**Comment by feugen24** [comment]
@gautema I get your points, I considered forking but I wanted your thoughts first. I suppose I'll go with forking and try to merge with changes from this repository later on.

 I'm working for a kind of proof of concept using event sourcing for one of our clients. In this context there will probably be other developers using the code and since ES/CQRS is not that mainstream each new small thing adds up to complexity/adoption in the sense that probably a developer could mentally translate Id to AggregateId but I try to reduce that effort as much as possible.

As a suggestion I tried learning from the 2 article links in the home project screen but the [Greg Young presentation](https://www.youtube.com/watch?v=whCk1Q87_ZI) was far more useful for me and it's closely related to how the source code looks, so you could consider linking it as a learning source.

**Comment by gautema** [comment]
I'll take a look at the presentation. And I'll consider renaming event id again.

**Comment by ppumkin** [comment]
I am having the same issue now.  It works brilliant with your InMemory Dictionary.. but I have not really found any body with a good example using this and the EventStore.org DB.. every body use the in memory one.

The problem is EventStore.org DB requires a stream name... Now I have struggling two days to try and get it working as your Framework from NuGet. But I had to buckle in today, download it and import the project into mine and make some change.

As great and simple this project is.. There is very little room to extend it ;( I have been trying to work around everything and managed in most part, as @feugen24 mentioned with some casting (covariance) on IEVent in the save on EventStore which works OK but for Get there is no interface element so I cannot rebuild the stream name based on shit I put in a covariant interface.

Also.. Is it expected the Aggregate ID changes when events are applied? This threw me off a bit.

`LoadFromHistory` in `AggregateRoot`

```
 ApplyEvent(e);
 Id = e.Id;
 Version++;
```

You apply the event, then set the AggregateId to the EventId?? (which in my case I am using EventStore.org DB and each event must have a different ID)

Will probably make some small changes and will have to maintain our own package.

**Thanks for a great framework any way.** 

Allot of people use it.. just for fun, try and get eventStore.org DB to work with your framework and save an example.. I wonder if you will run into the same problems as us?
