### ISSUE TITLE
Any work on adding Query handler providers/helper classes?

### ISSUE THREAD

**Issue by cloudybrain** [gautema/CQRSlite#80]
I've personally adhered to this pattern discussed in this article:

https://cuttingedge.it/blogs/steven/pivot/entry.php?id=92

And I found it to be incredibly simplistic compared to using a repository for my read operations.

**Comment by gautema** [comment]
Hi.

Are you talking about replacing the repository for the write side, or adding this to the read side? I have not done anything towards this so far. What exactly are you proposing to add? Since all the implementations of IQuery and IQueryHandler are specific to your domain, the only thing that would make sense to add is the QueryProcessor and maybe a few interfaces used by it.

**Comment by cloudybrain** [comment]
I was thinking of adding support classes to anyone willing to adopt the query handler approach, which could aid in fetching and saving to aggregates. I happen to like the flexibility that is offered with command handlers, and was thinking the same could be applied for queries as well.

**Comment by cloudybrain** [comment]
I was thinking of adding support classes to anyone willing to adopt the
query handler approach, which could aid in fetching and saving to
aggregates. I happen to like the flexibility that is offered with command
handlers, and was thinking the same could be applied for queries as well.

**Comment by gautema** [comment]
Hi. It took a while, but I took a look and decided this was something I could add, and finally had the time to create an API I liked, so I added it to the code. It's now in release 0.26.0
