### ISSUE TITLE
Why custom invoke?

### ISSUE THREAD

**Issue by damccull** [gautema/CQRSlite#81]
Why do you do `this.Invoke("Apply", @event);` in the AggregateRoot.ApplyChanges instead of creating a virtual Apply method with an empty body on the AggregateRoot that the derived classes would inherit and be able to override?

Is it just the caching benefit or is there a language limitation that I'm unaware of?

**Comment by gautema** [comment]
Hi.

I could have made a abstract method Apply(IEvent), but then you would have to do a switch case or similar to handle your events. I did however want the code to choose the correct implementation of the Apply-method. So the implementation should be Apply(CustomEvent) not Apply(IEvent). 

I also wanted the implementation to be optional to implement in case you don't need the results from the event applied to the aggregate. 

My first thought was using the something like ((dynamic)this).Apply(event), but that's not supported by the language, so I went with a custom invoke function instead. 

The ApplyEvent-method is however virtual, so you could override it if you want some custom implementation or faster execution.

**Comment by damccull** [comment]
Thanks for the quick reply! I'm trying to learn CQRS, but I want to know it from the ground up, so I'm trying to avoid actually using your framework. I am, however, trying to take lessons from it (and other blogs, sources, etc) while I implement my application by hand. Thanks for writing this an open sourcing it. I will admit the learning curve is steep, and I wish there was more and better documentation, but your code is clear and concise in most places, and even the spots that use more advanced C# are at least easy to understand what they do, if not how they do it.

**Comment by gautema** [comment]
I know the documentation is a bit lacking, but documentation is a bit less motivating to write in my spare time than code. Hopefully the included sample, the blogs linked to, the tests and the code it self will provide enough context to understand most things.

There is a bit of advanced C# in there, but I have tried at least to make those separated and fairly easy to understand. But some code has also been optimized a lot, since it's in hot spots, which makes it less readable.

Just ask if there's anything more you want to know.
